# Jetty
application.name=fpsoknad
context.path=/fpsoknad

# Auditlogger
auditlogger.vendor=Foreldrepenger
auditlogger.product=fpsoknad

dokgen.rest.base.url=http://fpdokgen

fpdokgen.base.url=http://fp-dokgen/fpdokgen
fpdokgen.scopes=api://prod-gcp.teamforeldrepenger.fp-dokgen/.default
