# Jetty
application.name=fpsoknad
context.path=/fpsoknad

# Auditlogger
auditlogger.vendor=Foreldrepenger
auditlogger.product=fpsoknad

dokgen.rest.base.url=http://fpdokgen

ny.fpdokgen.url=http://fp-dokgen/fpdokgen
ny.fpdokgen.scopes=api://prod-gcp.teamforeldrepenger.fp-dokgen/.default
TOGGLE_BRUK_NY_DOKGEN=false
