package no.nav.foreldrepenger.soknad.server.error;

public enum FeilKode {
    IKKE_TILGANG,
    DUPLIKAT_FORSENDELSE,
    MELLOMLAGRING,
    MELLOMLAGRING_VEDLEGG,
    MELLOMLAGRING_VEDLEGG_VIRUSSCAN_TIMEOUT,
    MELLOMLAGRING_VEDLEGG_PASSORD_BESKYTTET,
    KRYPTERING_MELLOMLAGRING;
}
