kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: fpsoknad
  namespace: {{namespace}}
  labels:
    team: {{namespace}}
spec:
  image: {{image}}
  port: 8080
  liveness:
    path: /fpsoknad/internal/health/isAlive
    initialDelay: 15
    periodSeconds: 10
    failureThreshold: 20
    timeout: 3
  readiness:
    path: /fpsoknad/internal/health/isReady
    initialDelay: 15
    periodSeconds: 10
    failureThreshold: 20
    timeout: 3
  prometheus:
    enabled: true
    path: /fpsoknad/internal/metrics/prometheus
  preStopHook:
    http:
      path: /fpsoknad/internal/health/preStop
  replicas:
    min: {{minReplicas}}
    max: {{maxReplicas}}
    scalingStrategy:
      cpu:
        thresholdPercentage: 80
  resources:
    limits:
      cpu: "{{limits.cpu}}"
      memory: "{{limits.mem}}"
    requests:
      cpu: "{{requests.cpu}}"
      memory: "{{requests.mem}}"
  kafka:
    pool: {{kafkaPool}}
  gcp:
    buckets:
      - name: {{tmpbucket}}
        lifecycleCondition:
          daysSinceCustomTime: 7
    sqlInstances:
      - type: POSTGRES_17
        databases:
          - name: fpsoknad
        tier: {{dbTier}}
        diskAutoresize: {{dbDiskAutoresize}}
        highAvailability: {{dbHighAvailability}}
        pointInTimeRecovery: {{dbPointInTimeRecovery}}
        collation: nb_NO.UTF8
  tokenx:
    enabled: true
  azure:
    application:
      enabled: true
      claims:
        extra:
          - "NAVident"
          - "azp_name"
        groups:
          {{#each groups as |group|}}
            - id: "{{group.uuid}}"
          {{/each}}
  env:
    - name: GCP_BUCKET_NAME
      value: {{tmpbucket}}
  envFrom:
    - secret: mellomlagring-kryptering # krypteringsnøkkel for mellomlagring
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: loki
        - id: elastic
  accessPolicy:
    inbound:
      rules:
        - application: engangsstonad
        - application: foreldrepengesoknad
        - application: svangerskapspengesoknad
        - application: foreldrepengeoversikt
        {{#if azure-token-generator}}
        - application: azure-token-generator
          namespace: nais
        {{/if}}
        - application: fp-swagger
          namespace: teamforeldrepenger
          cluster: {{environment}}-gcp
          permissions:
            scopes:
              - swagger
    outbound:
      rules:
        - application: fpdokgen
        - application: clamav
          namespace: nais-system
      external:
        - host: fpsak-api.{{environment}}-fss-pub.nais.io
        - host: fptilbake.{{environment}}-fss-pub.nais.io
        - host: pdl-api.{{environment}}-fss-pub.nais.io
        - host: {{dokarkivUrl}}
