CREATE TABLE DOKUMENT_METADATA (
    id BIGSERIAL PRIMARY KEY,
    FORSENDELSE_ID UUID NOT NULL,
    BRUKER_ID VARCHAR(255) NOT NULL,
    SAKSNUMMER VARCHAR(255),
    JOURNALPOST_ID VARCHAR(255),
    FORSENDELSE_STATUS VARCHAR(50) NOT NULL,
    FORSENDELSE_MOTTATT TIMESTAMP NOT NULL
);

CREATE UNIQUE INDEX IDX_DOKUMENT ON DOKUMENT_METADATA (FORSENDELSE_ID);
ALTER TABLE DOKUMENT_METADATA ADD CONSTRAINT PK_DOKUMENT_METADATA UNIQUE (FORSENDELSE_ID);

COMMENT ON TABLE DOKUMENT_METADATA IS 'Metadataene til dokumentene som fordeles';
COMMENT ON COLUMN DOKUMENT_METADATA.ID IS 'Primærnøkkel';
COMMENT ON COLUMN DOKUMENT_METADATA.FORSENDELSE_ID IS 'Unik ID for forsendelsen';
COMMENT ON COLUMN DOKUMENT_METADATA.BRUKER_ID IS 'ID til avsenderen av et dokument';
COMMENT ON COLUMN DOKUMENT_METADATA.SAKSNUMMER IS 'ID til fagsak et dokument knyttes mot';
COMMENT ON COLUMN DOKUMENT_METADATA.JOURNALPOST_ID IS 'ID til dokumentet i JOARK';
COMMENT ON COLUMN DOKUMENT_METADATA.FORSENDELSE_STATUS IS 'Status på dokumentforsendelse';
COMMENT ON COLUMN DOKUMENT_METADATA.FORSENDELSE_MOTTATT IS 'Tidspunktet forsendelsen ble mottatt hos NAV';

CREATE TABLE DOKUMENT (
    id BIGSERIAL PRIMARY KEY,
    FORSENDELSE_ID UUID NOT NULL,
    dokument_type_id VARCHAR(50) NOT NULL,
    BLOB BYTEA NOT NULL,
    ER_SØKNAD BOOLEAN,
    arkiv_filtype VARCHAR(50),
    BESKRIVELSE VARCHAR(150)
);

COMMENT ON TABLE DOKUMENT IS 'Tabell for lagring av dokumenter';
COMMENT ON COLUMN DOKUMENT.id IS 'Primærnøkkel';
COMMENT ON COLUMN DOKUMENT.FORSENDELSE_ID IS 'Unik ID for forsendelsen dokumentet tilhører';
COMMENT ON COLUMN DOKUMENT.dokument_type_id IS 'Type dokument';
COMMENT ON COLUMN DOKUMENT.BLOB IS 'Dokumentets innhold';
COMMENT ON COLUMN DOKUMENT.ER_SØKNAD IS 'Angir om dokumentet er en søknad';
COMMENT ON COLUMN DOKUMENT.arkiv_filtype IS 'Filtype for arkivering';
COMMENT ON COLUMN DOKUMENT.BESKRIVELSE IS 'Beskrivelse av dokumentet';

CREATE SEQUENCE SEQ_GLOBAL_PK INCREMENT BY 50 MINVALUE 2000000;
